// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBd3A31YjKyddMQWIJs5qV8bU6cbW_65SU',
    appId: '1:493808727661:web:6e881acbd64677153f3164',
    messagingSenderId: '493808727661',
    projectId: 'easyvote-71ed8',
    authDomain: 'easyvote-71ed8.firebaseapp.com',
    storageBucket: 'easyvote-71ed8.appspot.com',
    measurementId: 'G-Y3B8X8NZRB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5lIby9yk8iRVTpJnuH93gtm5f6uV9xVU',
    appId: '1:493808727661:android:d764f7ff1c82eee23f3164',
    messagingSenderId: '493808727661',
    projectId: 'easyvote-71ed8',
    storageBucket: 'easyvote-71ed8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7zYPEIIAMAJNYFmhPTIpj8tPzQ7jAWAg',
    appId: '1:493808727661:ios:981c0ba0d8acf0193f3164',
    messagingSenderId: '493808727661',
    projectId: 'easyvote-71ed8',
    storageBucket: 'easyvote-71ed8.appspot.com',
    iosBundleId: 'com.example.easyVote',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7zYPEIIAMAJNYFmhPTIpj8tPzQ7jAWAg',
    appId: '1:493808727661:ios:981c0ba0d8acf0193f3164',
    messagingSenderId: '493808727661',
    projectId: 'easyvote-71ed8',
    storageBucket: 'easyvote-71ed8.appspot.com',
    iosBundleId: 'com.example.easyVote',
  );

}